apps/account/urls.py
#zhouzhe {Administrator}
#DATE {2018/10/9}

from django.urls import path
from .import views

app_name = 'account'

urlpatterns = [
    path('login', views.LoginView.as_view(), name="login"),
    path('register', views.RegisterView.as_view(), name="register"),
    path('logout', views.logoutView, name="logout"),
    path('reset_password', views.ResetPasswordView.as_view(), name="reset_password"),
    path('update_password', views.UpdatePasswordView.as_view(), name="update_password"),
    path('graph_captcha', views.graph_captcha, name="graph_captcha"),
    path('sms_captcha', views.sms_captcha, name="sms_captcha"),

]

apps/course/urls.py
#zhouzhe {Administrator}
#DATE {2018/10/9}

from django.urls import path
from .views import index

app_name = 'course'
# reverse('new':index)
urlpatterns = [
    path('', index, name="index"),
]

apps/doc/urls.py
#zhouzhe {Administrator}
#DATE {2018/10/9}

from django.urls import path
from .views import index

app_name = 'doc'
# reverse('new':index)
urlpatterns = [
    path('', index, name="index"),
]

apps/news/urls.py
#zhouzhe {Administrator}
#DATE {2018/10/9}

from django.urls import path
from .views import index,search
from . import views

app_name = 'news'

# reverse('new':index)
urlpatterns = [
    path('', index, name="index"),
    path('new/detail/<int:news_id>',views.news_detail, name="news_detail"),
    path('news/add-comment/',views.AddNewsCommentView.as_view(), name="news_comment"),
    path('news/comment/',views.comment_list_with_news, name="comment_list_with_news"),
    path('news/list/',views.new_list, name="news_list"),
    path('search', search, name="search"),
]

djT/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('apps.news.urls')),
    path('course', include('apps.course.urls')),
    path('doc', include('apps.doc.urls')),
    path('account/', include('apps.account.urls')),
    path('admin_cms/', include('apps.admin_cms.urls')),
    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#
#https://docs.djangoproject.com/en/2.1/howto/static-files/

templates/base/font-base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}	{% endblock %}</title>

	<meta charset="utf-8">
    {% include 'base/link-base.html' %}
    {% block link %}   {% endblock %}

</head>

<body>
	<!-- header start -->
	<header id="header">
		<div class="mw1200 header-contain clearfix">
			<!-- logo start -->
			<h1 class="logo">
				<a href="javascript:void(0);" class="logo-title">Python</a>
			</h1>
			<!-- logo end -->
			<!-- nav start -->
			<nav class="nav">
				<ul class="menu">
					<li class="active"><a href="{% url 'news:index' %}">首页</a></li>
					<li><a href="{% url 'course:index' %}">在线课堂</a></li>
					<li><a href="{% url 'doc:index' %}">下载文档</a></li>
					<li><a href="{% url 'news:search' %}">搜索</a></li>
				</ul>
			</nav>
			<!-- nav end -->
			<!-- login start -->
			<div class="login-box">
                {% if user.is_authenticated %}
                    <div class="author">
                        <i class="PyWhich py-user"></i>
                        <span>{{ user.username }}</span>
                        <ul class="author-menu">
                            {% if user.is_staff %}
                                <li><a href="{% url 'admin_cms:admin_cms' %}">后台管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'account:logout' %}">退出登录</a></li>
                        </ul>
				    </div>
                 {% else %}
                    <div>
					<i class="PyWhich py-user"></i>
					<span>
						<a href="{% url 'account:login' %}" class="login">登录</a> /
						<a href="{% url 'account:register' %}" class="register">注册</a>
					</span>
				</div>
                {% endif %}


				<!-- loged start -->

				<!-- loged end -->
			</div>
			<!-- login end -->
		</div>
	</header>

	<!-- header end -->
{% block main %}　　{% endblock %}

	<!-- footer start -->
	<footer id="footer">
		<div class="footer-box">
			<div class="footer-content">
				<p class="top-content">
					<span class="link">
						<a href="javascript:void(0)">关于Python</a> |
						<a href="javascript:void(0)">我就是我</a> |
						<a href="javascript:void(0)">人生苦短</a> |
						<a href="javascript:void(0)">我要飞翔</a>
					</span>
					<span class="about-me">关于我: <i class="PyWhich py-wechat"></i> 付帅帅</span>
				</p>
				<p class="bottom-content">
					<span>地址： xxxx</span>
					<span>联系方式: <a href="tel:400-1567-315">400-1567-315</a> (24小时在线)</span>
				</p>
			</div>
			<p class="copyright-desc">
				Copyright &copy; 2008 - 2018 xxx有限公司. All Rights Reserved
			</p>
		</div>
	</footer>
	<!-- footer end -->
	<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
	<script src="/static/js/base/message.js"></script>
	<script src="/static/js/base/common.js"></script>


    {% block script %}

    {% endblock %}
</body>
</html>

templates/base/link-base.html
	<link rel="stylesheet" href="/static/css/base/reset.css">
	<link rel="stylesheet" href="/static/css/base/common.css">
	<link rel="stylesheet" href="/static/css/base/side.css">
	<link rel="stylesheet" href="http://at.alicdn.com/t/font_684044_un7umbuwwfp.css">

{#    网站logog#}
{#    <link rel="stylesheet" href="" class="favico">#}

templates/base/side-base.html
<!-- side start -->
<aside class="side">
    <div class="side-activities">
        <h3 class="activities-title">在线课堂<a href="javascript:void(0)">更多</a></h3>
        <div class="activities-img">
            <a href="javascript:void(0);" target="_blank">
                <img src="https://res.shiguangkey.com//file/201804/26/20180426142628123364782.jpg" alt="title">
            </a>
            <p class="activities-tips">对话国外小姐姐</p>
        </div>
        <ul class="activities-list">
            <li>
                <a href="javascript:void(0);" target="_blank">
                    <span class="active-status active-start">报名中</span>
                    <span class="active-title"> Python基础班</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);" target="_blank">
                    <span class="active-status active-end">已结束</span>
                    <span class="active-title">法语基础班</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="side-attention clearfix">
        <h3 class="attention-title">关注我</h3>
        <ul class="side-attention-address">
            <li>
                <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-GitHub"></i>付帅帅</a>
            </li>
            <li>
                <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-zhihu"
                                                                 style="color:rgb(0, 108, 226);"></i>handsomeFu</a>
            </li>
            <li>
                <a href="javascript:void(0);" target="_blank"><i class="PyWhich py-weibo"
                                                                 style="color:rgba(245, 100, 103)"></i>付帅帅</a>
            </li>
        </ul>
        <div class="side-attention-qr">
            <p>扫码关注</p>
        </div>
    </div>
    <div class="side-hot-recommend">
        <h3 class="hot-recommend">热门推荐</h3>
        <ul class="hot-news-list">
            <li>
                <a href="javascript:void(0)" class="hot-news-contain clearfix">
                    <div class="hot-news-thumbnail">
                        <img src="http://a1.qpic.cn/psb?/V13Pc4324LdOaJ/EaLrCUqB.T14wh*zo.6jalz0OlnGr7k*Ka5MzNoWnsY!/b/dAgBAAAAAAAA"
                             alt="">
                    </div>
                    <div class="hot-news-content">
                        <p class="hot-news-title">湖南信息技术类中高职衔接培训班来访潭州，探索互联网+教育新模式</p>
                        <div class="hot-news-other clearfix">
                            <span class="news-type">热点</span>
                            <time class="news-pub-time" datetime="6-16">6月16日</time>
                            <span class="news-author">Which</span>
                        </div>
                    </div>
                </a>
            </li>
            <li>
                <a href="javascript:void(0)" class="hot-news-contain clearfix">
                    <div class="hot-news-thumbnail">
                        <img src="http://a1.qpic.cn/psb?/V13Pc4324LdOaJ/EaLrCUqB.T14wh*zo.6jalz0OlnGr7k*Ka5MzNoWnsY!/b/dAgBAAAAAAAA"
                             alt="">
                    </div>
                    <div class="hot-news-content">
                        <p class="hot-news-title">湖南信息技术类中高职衔接培训班来访潭州，探索互联网+教育新模式</p>
                        <div class="hot-news-other clearfix">
                            <span class="news-type">热点</span>
                            <time class="news-pub-time" datetime="6-16">6月16日</time>
                            <span class="news-author">Which</span>
                        </div>
                    </div>
                </a>
            </li>
        </ul>
    </div>
</aside>
<!-- side end -->