apps/news/urls.py
#zhouzhe {Administrator}
#DATE {2018/10/9}

from django.urls import path
from .views import index,search
from . import views

app_name = 'news'

# reverse('new':index)
urlpatterns = [
    path('', index, name="index"),
    path('new/detail/<int:news_id>',views.news_detail, name="news_detail"),
    path('news/add-comment/',views.AddNewsCommentView.as_view(), name="news_comment"),
    path('news/comment/',views.comment_list_with_news, name="comment_list_with_news"),
    path('news/list/',views.new_list, name="news_list"),
    path('search', search, name="search"),
]

djT/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include('apps.news.urls')),
    path('course', include('apps.course.urls')),
    path('doc', include('apps.doc.urls')),
    path('account/', include('apps.account.urls')),
    path('admin_cms/', include('apps.admin_cms.urls')),
    #static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)[0],

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#
#https://docs.djangoproject.com/en/2.1/howto/static-files/

apps/news/models.py
from django.db import models

# 新闻标签model

class NewTag(models.Model):
    name = models.CharField(max_length=30)
    # 创建时间
    create_data = models.DateTimeField(auto_now_add=True)
    # 用于判断是否删除 ，删除了设置为False updata(id_delete=False)
    is_delete = models.BooleanField(default=True)


# 新闻model

class News(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    # 缩略图的url地址
    thumbnail_url = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    is_delete = models.BooleanField(default=True)
    # on_delete=models.SET_NULL 置空
    tag = models.ForeignKey("NewTag", on_delete=models.CASCADE)
    author = models.ForeignKey("account.User", on_delete=models.CASCADE)

    class Meta:

        # 新闻倒序 -id 默认是正序  ["-id"]
        ordering = ("-id",)


# 新闻评论model
class NewsComment(models.Model):
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    # 新闻评论所属的新闻
    author = models.ForeignKey('account.User', on_delete=models.CASCADE)
    # 通过新闻找评论 用comments 没写related_name用News_set,反向查找的名子
    news = models.ForeignKey("News", on_delete=models.CASCADE, related_name="comments")

    class Meta:
        ordering = ['-id']

apps/news/forms.py
from django import forms
from apps.forms import FormMinin

# 新闻评论验证

class NewsCommentForm(forms.Form,FormMinin):
    # 传入的新闻id
    news_id = forms.IntegerField(error_messages={"required": "新闻id不能为空"})
    # 传入的新闻的评论
    content = forms.CharField(error_messages= {"required": "新闻评论内容不能为空"})

apps/news/views.py
from django.shortcuts import render
from django.views import View
from .models import NewTag,News,NewsComment
from django.http import Http404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from apps.news.forms import NewsCommentForm
from utils import json_status
from apps.news.serializers import NewsCommentSerializers,NewsSerializers
from django.contrib.auth.decorators import login_required
from utils.decorators import ajax_login_required
from django.conf import settings

def index(request):
    news_tags = NewTag.objects.filter(is_delete=True).all()
    # defer不查新闻内容字段,  select_related预先查询，会先执行
    newses = News.objects.defer("content").select_related("tag","author").filter(is_delete=True).all()[0: settings.ONE_PAGE_NEWS_COUNT]
    content = {"news_tags":news_tags,"newses":newses}

    from datetime import datetime
    from django.utils.timezone import now
    print(datetime.now())       #2018-10-22 10:18:38.778725 系统当前时间
    print(now())                #2018-10-22 02:18:38.779494+00:00  会跟据settings里的时区默认减 8

    return render(request,'news/index.html',context=content)


def new_list(request):
    page = int(request.GET.get("page",1))
    tag_id = int(request.GET.get("tag_id",0))
    start_page = settings.ONE_PAGE_NEWS_COUNT * (page-1)
    end_page  = start_page + settings.ONE_PAGE_NEWS_COUNT
    print(start_page, end_page, tag_id)
    if tag_id:
        newses = News.objects.defer("content").select_related("tag", "author").filter(is_delete=True, tag=tag_id).all()[start_page:end_page]
        print("tag_id",newses)
    else:
        newses = News.objects.defer("content").select_related("tag","author").filter(is_delete=True).all()[start_page:end_page]
    serializer = NewsSerializers(newses, many=True)

    return json_status.result(message="ok",data={"newses": serializer.data})



def news_detail(request,news_id):
    try:
        print(news_id)
        # news = News.objects.filter(id=news_id, is_delete=True).first()#空值返回None
        news = News.objects.get(id=news_id)
        return render(request,"news/news_detail.html", context={"news":news})
    except News.DoesNotExist:
        # django对于找不到的url都会跳到这个页面，必须是settings.DEBUG = False
        raise Http404



@method_decorator([csrf_exempt, ajax_login_required], name='dispatch')
class AddNewsCommentView(View):
    def post(self,request):
        form = NewsCommentForm(request.POST)
        if form.is_valid():
            news_id = form.cleaned_data.get("news_id")
            content = form.cleaned_data.get("content")
            print(news_id,content)
            news = News.objects.filter(id = news_id).first()
            if news:
                res = NewsComment.objects.create(content=content,author=request.user,news=news)
                print("res:",res)
                serializer = NewsCommentSerializers(res)
                print("serializer",serializer.data)
                return json_status.result(message="添加成功",data=serializer.data)
            return json_status.params_error(message="新闻不存在")
        return json_status.params_error(message=form.get_error())

# 后端拿到新闻id 返回json 前 端遍历 restfull
def comment_list_with_news(request):
    news_id = request.GET.get("news_id")
    print(news_id)
    # 根据新闻的new_id晒对应的评论
    news = News.objects.filter(id=news_id).first()
    if news:
        # 获取当前新闻下所有的评论
        news_comments = news.comments.all()
        # print(news_comments)    #<QuerySet [<NewsComment: NewsComment object (1)>]>
        #values()将Queryset转为json
        # print(news_comments.values()) #<QuerySet [{'create_time': datetime.datetime(2018, 10, 23, 2, 22, 26, 674233, tzinfo=<UTC>), 'news_id': 1, 'author_id': 1, 'content': '这是新闻id为1的第一条评 论', 'id': 1}]>
        # news_comments = list(news_comments.values())
        # for news_comment in news_comments:
            # 每天条评论的json,反回的并没有做者，只有作者的id
            #{'content': '这是新闻id为1的第一条评 论', 'create_time': datetime.datetime(2018, 10, 23, 2, 22, 26, 674233, tzinfo= < UTC >),
            # print(news_comment)
        serializers = NewsCommentSerializers(news_comments,many=True)
        print(serializers)
        print("_____________________________")
        print(serializers.data)
        return json_status.result(message="OK",data=serializers.data)
    return json_status.params_error(message="新闻id找不到")




def search(request):
    return render(request,'news/search.html')

templates/news/index.html
{% extends 'base/font-base.html' %}
{% load news_data_filter %}
{% block title %}
首页
{% endblock %}

{% block link %}
	<link rel="stylesheet" href="/static/css/news/index.css">
{% endblock %}

{% block main %}
    <!-- main start -->
    <main id="main">
        <div class="w1200 clearfix">
            <!-- main-contain start  -->
            <div class="main-contain">
                <!-- banner start -->
                <div class="banner">
                    <ul class="pic">
                        <li style="display:block;"><a href="javascript:void(0);"><img
                                src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084920&di=674290bae4e0f33ac252cff0ef95ec3f&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F3%2F57a1548ddd149.jpg"
                                alt="test"></a></li>
                        <li><a href="javascript:void(0);"><img
                                src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2126622145,1468696620&fm=26&gp=0.jpg"
                                alt="test"></a></li>
                        <li><a href="javascript:void(0);"><img
                                src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=2775064463,1890836574&fm=26&gp=0.jpg"
                                alt="test"></a></li>
                        <li><a href="javascript:void(0);"><img
                                src="https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=3182804019,3354432715&fm=26&gp=0.jpg"
                                alt="test"></a></li>
                    </ul>
                    <a href="javascript:void(0);" class="btn prev">
                        <i class="PyWhich py-arrow-left"></i></a>
                    <a href="javascript:void(0);" class="btn next">
                        <i class="PyWhich py-arrow-right"></i></a>
                    <ul class="tab">
                        <li class="active"></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                </div>
                <!-- banner end -->
                <!-- content start -->
                <div class="content">
                    <!-- recommend-news start -->
                    <ul class="recommend-news">
                        <li>
                            <a href="javascript:void(0);" target="_blank">
                                <div class="recommend-thumbnail">
                                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg"
                                         alt="title">
                                </div>
                                <p class="info">人生苦短，我用Python</p>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" target="_blank">
                                <div class="recommend-thumbnail">
                                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg"
                                         alt="title">
                                </div>
                                <p class="info">人生苦短，我用Python</p>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" target="_blank">
                                <div class="recommend-thumbnail">
                                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1537264084300&di=8f55d3ddef645bd7de02024e63224cd3&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fblog%2F201506%2F09%2F20150609130218_cKEZm.jpeg"
                                         alt="title">
                                </div>
                                <p class="info">人生苦短，我用Python</p>
                            </a>
                        </li>
                    </ul>
                    <!-- recommend-news end -->
                    <!--  news-nav start-->
                    <nav class="news-nav">
                        <ul class="clearfix">
                            <li class="active"><a href="javascript:void(0)">最新资讯</a></li>
                            {% for news_tag in news_tags %}
                                <li><a href="javascript:void(0)" data-id="{{ news_tag.id }}">{{ news_tag.name }}</a></li>
                            {% endfor %}


                        </ul>
                    </nav>
                    <!--  news-nav end -->
                    <!-- news-contain start -->
                    <div class="news-contain">
                        <ul class="news-list">
                            {% for news in newses %}
                                <li class="news-item">
                                <a href="javascript:void(0);" class="news-thumbnail" target="_blank">
                                    <img src="{{ news.thumbnail_url }}"
                                         alt="{{ news.title }}" title="{{ news.title }}">
                                </a>
                                <div class="news-content">
                                    <h4 class="news-title"><a href="{% url 'news:news_detail' news_id=news.id %}">{{ news.title }}</a></h4>
                                    <p class="news-details">{{ news.desc }}</p>
                                    <div class="news-other">
                                        <span class="news-type">{{ news.tag.name }}</span>
                                        <span class="news-time">{{ news.pub_time|data_format }}</span>
                                        <span class="news-author">{{ news.author.username }}</span>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    <!-- news-contain end -->
                    <!-- btn-more start -->
                    <a href="javascript:void(0);" class="btn-more" id="btn-more" data-page="2">加载更多</a>
                    <!-- btn-more end -->
                </div>
                <!-- content end -->
            </div>
            <!-- main-contain  end -->
            <!-- side start -->
                {% include 'base/side-base.html' %}
            <!-- side end -->
        </div>
    </main>
    <!-- main end -->
{% endblock %}


{% block script %}

    <script src="/static/js/news/index.js"></script>

{% endblock %}


templates/news/news_detail.html
{% extends 'base/font-base.html' %}
{% load news_data_filter %}
{% block link %}
    <link rel="stylesheet" href="/static/css/news/news_detail.css">
{% endblock %}

{% block main %}
    <!-- main start -->
    <main id="main">
        <div class="w1200 clearfix">
            <!-- news-contain start  -->
            <div class="news-contain">
                <h1 class="news-title">{{ news.title }}</h1>
                <div class="news-info">
                    <div class="news-info-left">
                        <span class="news-author">{{ news.author.username }}</span>
                        <span class="news-pub-time">{{ news.pub_time|data_format }}</span>
                        <span class="news-type">{{ news.tag.name }}</span>
                    </div>
                </div>
                <article class="news-content">
{#                    safe 解析标签#}
                    {{ news.content|safe }}
                </article>
                <div class="comment-contain">
                    <div class="comment-pub clearfix">
                        <div class="new-comment">
                            文章评论(<span class="comment-count">0</span>)
                        </div>
                        {% if user.is_authenticated %}
                           <div class="comment-control logged-comment">
                            <input type="text" placeholder="请填写评论">
                           </div>
                        {% else %}
                           <div class="comment-control please-login-comment">
                            <input type="text" placeholder="请登录后参加评论" readonly>
                            </div>
                        {% endif %}

                        <button class="comment-btn" data-news-id="{{ news.id }}">发表评论</button>
                    </div>
                    <ul class="comment-list">

                    </ul>
                </div>

            </div>
            <!-- news-contain end  -->
            <!-- side start -->
            {% include 'base/side-base.html' %}
            <!-- side end -->
        </div>
    </main>
    <!-- main end -->
{% endblock %}

{% block title %}
{{ news.title }}
{% endblock %}

{% block script %}
    <script src="/static/js/news/newsdateil.js"></script>
{% endblock %}

templates/news/search.html

{% extends 'base/font-base.html' %}

{% block title %}
搜索页
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="/static/css/news/search.css">
{% endblock %}

{% block main %}
    <!-- main start -->
    <main id="main">
        <div class="w1200 clearfix">
            <!-- main-contain start  -->
            <div class="main-contain ">
                <!-- search-box start -->
                <div class="search-box">
                    <form action="" style="display: inline-flex;">
                        <input type="search" placeholder="请输入要搜索的内容" name="q" class="search-control">
                        <input type="submit" value="搜索" class="search-btn">
                    </form>
                    <!-- 可以用浮动 垂直对齐 以及 flex  -->
                </div>
                <!-- search-box end -->
                <!-- content start -->
                <div class="content">
                    <!-- search-list start -->
                    <div class="search-result-list hide">
                        <h2 class="search-result-title">
                            搜索结果 <span style="font-weight: 300;"></span>
                        </h2>
                        <ul class="news-list">
                            <li class="news-item clearfix">
                                <a href="javascript:void(0);" class="news-thumbnail" target="_blank">
                                    <img src="https://res.shiguangkey.com//file/201808/13/20180813153406778113487.png">
                                </a>
                                <div class="news-content">
                                    <h4 class="news-title"><a href="javascript:void(0);">新闻标题</a></h4>
                                    <p class="news-details">新闻详情新闻详情新闻详情新闻详情新闻详情</p>
                                    <div class="news-other">
                                        <span class="news-type">分类名</span>
                                        <span class="news-time">发布时间</span>
                                        <span class="news-author">作者</span>
                                    </div>
                                </div>
                            </li>
                            <li class="news-item clearfix">
                                <a href="javascript:void(0);" class="news-thumbnail" target="_blank">
                                    <img src="https://res.shiguangkey.com//file/201808/13/20180813153406778113487.png">
                                </a>
                                <div class="news-content">
                                    <h4 class="news-title"><a href="javascript:void(0);">新闻标题</a></h4>
                                    <p class="news-details">新闻详情新闻详情新闻详情新闻详情新闻详情</p>
                                    <div class="news-other">
                                        <span class="news-type">分类名</span>
                                        <span class="news-time">发布时间</span>
                                        <span class="news-author">作者</span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <!-- search-list end -->
                    <!-- news-contain start -->
                    <div class="news-contain">
                        <div class="hot-recommend-list">
                            <h2 class="hot-recommend-title">热门推荐</h2>
                            <ul class="news-list">
                                <li class="news-item clearfix">
                                    <a href="javascript:void(0);" class="news-thumbnail">
                                        <img src="https://res.shiguangkey.com//file/201808/13/20180813153406778113487.png">
                                    </a>
                                    <div class="news-content">
                                        <h4 class="news-title">
                                            <a href="javascript:void(0);">新闻标题</a>
                                        </h4>
                                        <p class="news-details">
                                        </p>
                                        <div class="news-other">
                                            <span class="news-type">分类名</span>
                                            <span class="news-time">发布时间</span>
                                            <span class="news-author">作者</span>
                                        </div>
                                    </div>
                                </li>
                                <li class="news-item clearfix">
                                    <a href="javascript:void(0);" class="news-thumbnail">
                                        <img src="https://res.shiguangkey.com//file/201808/13/20180813153406778113487.png">
                                    </a>
                                    <div class="news-content">
                                        <h4 class="news-title">
                                            <a href="javascript:void(0);">新闻标题</a>
                                        </h4>
                                        <p class="news-details">
                                        </p>
                                        <div class="news-other">
                                            <span class="news-type">分类名</span>
                                            <span class="news-time">发布时间</span>
                                            <span class="news-author">作者</span>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- news-contain end -->
                </div>
                <!-- content end -->
            </div>
            <!-- main-contain  end -->
            <!-- side start -->
                {% include 'base/side-base.html' %}
            <!-- side nd -->
        </div>
    </main>
    <!-- main end -->
{% endblock %}

{% block script %}

{% endblock %}
